version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: 'docker'
      DATABASE_NAME: 'db'
      DATABASE_USER: 'david'
      DATABASE_PASSWORD: 'password'
    container_name: Dockerfile
    volumes:
      - ./tp1:/app
    networks:
      - itsv

  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: 'david'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'bd_tp1'
      container_name: 'mysql'
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      itsv:
        aliases:
          - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
    networks:
      - itsv

networks:
  itsv:
    driver: bridge